### ISSUE TITLE
Need a way to add templateFunc in requestHandle

### ISSUE THREAD

**Issue by syklevin** [iris-contrib/template#3]
Thanks for the great web framework!

i know we could assign templateFuncs during construct template engine. but sometimes we need to add some ad-hoc templateFuncs based on each request params for template rendering.

**Comment by kataras** [comment]
Yes, many people asking me this, to have access to the `context` directly, this will cause performance issues and security issues, so I will never do that **BUT** if you want to pass **request params** or anything else, why not just pass it as the second parameter of the `context.Render` ?

```go
func myfileHandler(ctx *iris.Context){
   ctx.Render("myfile.html", iris.Map{"params": ctx.Params})
}
```

**Comment by kataras** [comment]
Yes, many people asking me this, to have access to the `context` directly, this will cause performance issues and security issues, so I will never do that **BUT** if you want to pass **request params** or anything else, why not just pass it as the second parameter of the `context.Render` ?

```go
func myfileHandler(ctx *iris.Context){
   ctx.Render("myfile.html", iris.Map{"params": ctx.Params})
}
//...

func myTemplateFunc(params iris.PathParameters) {
       //....
}
```


```
{{myTemplateFunc params}}
```

**Comment by kataras** [comment]
Yes, many people asking me this, to have access to the `context` directly, this will cause performance issues and security issues, so I will never do that **BUT** if you want to pass **request params** or anything else, why not just pass it as the second parameter of the `context.Render` ?

```go
func myfileHandler(ctx *iris.Context){
   ctx.Render("myfile.html", iris.Map{"params": ctx.Params})
}
//...

func MyTemplateFunc(params iris.PathParameters) {
       //....
}
```


```
{{MyTemplateFunc params}}
```

**Comment by kataras** [comment]
Yes, many people asking me this, to have access to the `context` directly, this will cause performance issues and security issues, so I will never do that **BUT** if you want to pass **request params** or anything else, why not just pass it as the second parameter of the `context.Render` ?

```go
func myfileHandler(ctx *iris.Context){
   ctx.RenderWithStatus(iris.StatusOK, "myfile.html", iris.Map{"params": ctx.Params})
}
//...

func MyTemplateFunc(params iris.PathParameters) {
       //....
}
```


```
{{MyTemplateFunc params}}
```
